from vialGame import vialGame

test = vialGame(isTest=True)

## Testing input ##
test.printGame()
test.move(1,6)
test.printGame()
test.undoLastMove()
test.printGame()
test.move(1,6)
test.printGame()
test.move(3,6)
test.printGame()
test.undoLastMove()
test.printGame()
test.undoLastMove()
test.printGame()
test.undoLastMove()
test.printGame()
test.move(1,6)
test.printGame()
test.move(3,6)
test.printGame()
test.move(1,6)
test.printGame()
test.move(3,6)
test.printGame()
test.undoLastMove()
test.printGame()
test.undoLastMove()
test.printGame()
test.undoLastMove()
test.printGame()
test.undoLastMove()
test.printGame()
test.undoLastMove()
test.printGame()
test.undoLastMove()
test.printGame()
